### ISSUE TITLE
Country Display Errors

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#11]
- [ ] Office of Co-operative Societies of Papua New Guinea (OCS PNG) is displayed when Africa Super Region is filtered.
- [ ] The dialog does not display the county with the rest of the address.
- [ ]  Geocoding wrong for 
  - [ ] Economic and Social Development Center of Palestine is wrong.
  - [ ] Con-Federation (CNCTL)
  - [ ] Tose'e Ta'avon Bank (T.T. Bank)
  - [ ] Pishgaman Cooperative Union (PCU)
  - [ ] Palestinian Agriculture Cooperative Union (PACU)

**Comment by wu-lee** [comment]
Ok:
- Papua New Guinea seems to be misclassified as being in East Africa. I think it should be in Oceania, in Asia+Pacific (`I-AP-OC`). Will fix.
- Country in dialog: will check, presumably the result of losing `country` in favour of `countryId`

Geocoding:
- ESDC of Palestine: their website font page says their address is "Al Ersal, Al-Tallah Building, Old Birzeit Street, Opposite to Oud Café," (with "Ramallah, West Bank, 4518 Al-Bireh, Palestine" visible only on their Contact Us page; whereas the ICA say they are at "PO Box 4518 Opposite Ministry of Women's Affairs Ramallah Al-Balou, Al-Bireh". Different, although obviously neither are in France, which is where our geolocator says it is.
- GeoAPIfy doesn't perform so well on either of those addresses - I'm not sure if it even finds the right one at all, but there are candidates in the UK and US too, even adding "State of Palestine" gets one in the UK (bizarrely, it matches Old Street in London)
- CNCTL: likewise, it's in Timor-Leste, not France. GeoAPIfy also unable to get the exact address, although it does find Dili and a few addresses therein if the address from the dialog has Timor-Leste added.
- Note: our geolocator *does* include the country in the address, even if the dialog doesn't
- T.T. Bank: Should be Tehran, Iran not New York, USA. GeoAPIfy struggles with the address again, even with Iran included. I think it's the weird number, and the lack of commas. Although it can get a 100% match of the address if punctuation and country included, it gets two hits, one for each end of a very long street (and it's finding the street, not the specific address)
- PCU: GeoAPIfy struggling again
- PACU: GeoAPIfy does a little better, finding the street

Overall, these geocoding issues seem to stem from a combination of the exact address formatting we were given by the ICA (which can miss out commas or have word ordering which seem to make a difference), and GeoAPIfy's limitations even given a good address.

**Comment by ColmMassey** [comment]
I'll let the ICA know that the Iranian & Palestinian addresses need manual lon lats to be set in the file.

**Comment by wu-lee** [comment]
Just to compare, searching on google maps:
- ESDC:
  - "PO Box 4518 Opposite Ministry of Women's Affairs Ramallah Al-Balou, Al-Bireh" - finds city of Al-Birah
  - "PO Box 4518, Ramallah, Al-Balou, Al-Bireh, State of Palestine" - ditto
  - "PO Box 4518, Ramallah, West Bank, 4518 Al-Bireh, Palestine" - ditto
- CNCTL:
  - "Rue Marconi, Fatuhada Dili 670" - finds Dili, not the right street tho
  - "Con-Federation, Fatuhada Dili, Díli, Timor-Leste" -ditto, 
  - "con-federation, timor leste" - Google seems to have trouble finding *anything*
- T.T. Bank:
  - "No. 271 Mirdamad Blvd Tehran 1918934351" - doesn't like the number, throws it off
  -  "No. 271 Mirdamad Blvd Tehran " this address is found ok
- PACU:
  -  "Al-Bireh, Nablus Street Across the Netherlands Embassy, State of Palestine" - throws google off, finds the street Nablus and the city.
  - "Al-Bireh, Nablus Street, State of Palestine" - finds the location Al-Bireh, no the street
  - "Nablus Street, Al-Bireh, State of Palestine" - finds what seems to be a long street
- PCU:
  - "Pishgaman Building, No. 14 Ordibenesht St., Parkway Tehran 1986613114, Iran" - just finds Tehran
  - "Pishgaman Building, No. 14 Ordibenesht St., Parkway Tehran, Iran" - just finds Tehran
  - "No. 14 Ordibenesht St., Parkway Tehran, Iran" - finds the exact address

So Google does better, but many of the addresses only really work if they're formatted sensibly, and getting that right sometimes requires a few manual tweaks.

I'd conclude that GeoAPIfy isn't doing too badly given the input, except in a few cases.  Ideally we'd not be relying on addresses like these though!

**Comment by ColmMassey** [comment]
> Overall, these geocoding issues seem to stem from a combination of the exact address formatting we were given by the ICA (which can miss out commas or have word ordering which seem to make a difference), and GeoAPIfy's limitations even given a good address.

Can you create an Issue for proposed improvements to our geocoding setup and add a link to this Issue?

**Comment by ColmMassey** [comment]
> Can you create an Issue for proposed improvements to our geocoding setup and add a link to this Issue?

For later...

**Comment by wu-lee** [comment]
Ok: https://github.com/SolidarityEconomyAssociation/open-data/issues/70

**Comment by wu-lee** [comment]
Papua New Guinea re-categorised, data redeployed, now doesn't appear as part of Africa.

Country names now appearing in dialog.

Regarding regions: matching up the country/regions/super-regions in the current data set to our list of these things, they seem to agree for all but Papua NG. Of course, our list is longer, and there could still be mistakes in the categorisations of countries which aren't in the current ICA data.

**Comment by ColmMassey** [comment]
> Papua New Guinea re-categorised, data redeployed, now doesn't appear as part of Africa.

i don't think it has been redeployed properly. It is still there even in anonymous browsers instance.

**Comment by wu-lee** [comment]
I've cleared the cache on dev.ica - I think that's done the trick. See what you think?

**Comment by ColmMassey** [comment]
That did the trick.

**Comment by ColmMassey** [comment]
>Country names now appearing in dialog.
Not seeing this in latest deployed build

**Comment by wu-lee** [comment]
> Not seeing this in latest deployed build

Ah, I see something didn't get committed and pushed to the ica-project repo - should I push this now, or avoid udpdates as you requested via Whats App?

**Comment by ColmMassey** [comment]
Leave until they have had a look at current build.

**Comment by ColmMassey** [comment]
> Leave until they have had a look at current build.

You can push to the dev.ica-youth-network though.
