### ISSUE TITLE
Create Mockup to show lining between ICA members and OCDC CDO Map

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#14]
We are pitching for the ICA/OCDC tender. See https://drive.google.com/file/d/12nwR9_V68nFIqZjqJV6XvlLwNYHdj4m1/view?usp=sharing

We want to show what it would look like if in the dialog for each ICA member on the ICA members' map which was also Cooperative Develpment Organisation (CDO) an entry was included indicating this and it was possible to link to the proposed dedicated map of international CDOs. WHen that link was cliscked the new map opened and the CDO in questions was prehighrlighted and centreed in the map. In it's dialog a similar link back to the ICA members map was present.

**Comment by ColmMassey** [comment]
![CDO](https://user-images.githubusercontent.com/1162642/154122566-5694ff58-06dc-4e00-9810-77857601092e.png)

**Comment by ColmMassey** [comment]
But needs to look like it is embedded in the ICA website  https://www.ica.coop/en/our-members/search-our-members

And make another page which is distincty OCDC

**Comment by ColmMassey** [comment]
Hi @MelissaMc20.  Any progress on this? It's needed for tomorrow.

**Comment by MelissaMc20** [comment]
@ColmMassey https://xd.adobe.com/view/109ca7d6-df77-4556-8a92-db099a7ceb5d-45cf/?fullscreen 
Is this okay? I've got time to add in anything extra you might need for example, the ability to click on other markers etc.

**Comment by ColmMassey** [comment]
Hopefully this will do the trick.
