### ISSUE TITLE
Prepare launch version of ICA map.

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#6]
We need to get it all looking sweet on dev. 

- [x] Latest data - https://github.com/SolidarityEconomyAssociation/ica-project/issues/4
- [x]  Logo -  https://github.com/SolidarityEconomyAssociation/ica-project/issues/5
- [x] Thunderburd tiles using SEA account https://github.com/SolidarityEconomyAssociation/technology-and-infrastructure/issues/55
- [x] Carefully mirror to production server.

**Comment by ColmMassey** [comment]
Okay, when is a good time to mirror it to prod. Some time after hours, where I have a chance to test it and you would have time to fix any cache-whakamoles that may appear!

**Comment by wu-lee** [comment]
Could do it now. Is it after hours now?  Otherwise, after about 9?

**Comment by ColmMassey** [comment]
> Could do it now. Is it after hours now? Otherwise, after about 9?

Sorry. Missed that suggestion. Was shattered last night and didn't see this til too late. Want to try ths evening?

**Comment by wu-lee** [comment]
Ok, could do it before cooking dinner at 5.30ish, or after at 9 or later.

**Comment by ColmMassey** [comment]
> 
> 
> Ok, could do it before cooking dinner at 5.30ish, or after at 9 or later.

Okay. Before cooking. I can check and report any bugs I see and you could address them after 9:00?

**Comment by wu-lee** [comment]
Ok, will let you know when deployed.

**Comment by wu-lee** [comment]
Ok, just deployed ica-project with pre-safari-fix version of sea-map (0.1.61) here:

https://ica.solidarityeconomy.coop/

Just rebuilding the production data...

**Comment by wu-lee** [comment]
Ok, prod data deployed too now.

**Comment by ColmMassey** [comment]
Looking good on anonymous browser instance or when looking at https://prod.ica.solidarityeconomy.coop/. But it's still showing old version of sea-map SEA Map Version: 0.1.57 in regular browser looking at https://ica.solidarityeconomy.coop/

**Comment by wu-lee** [comment]
Latter deffo says sea-map v0.1.61 when I visit it.  Suspect naughty browser caching...

What browser is this? Can you open the page with the debug console open to the networking tab? Check for signs of caching, and look sat map-app.js specifically?

![image](https://user-images.githubusercontent.com/67825/100144104-32f3bc00-2e8e-11eb-8242-ead18c976125.png)

**Comment by wu-lee** [comment]
I notice I also have the "disable cache" box checked in that screenshot.

**Comment by ColmMassey** [comment]
> What browser is this?

Firefox on Windows 10

**Comment by ColmMassey** [comment]
> Check for signs of caching, and look sat map-app.js specifically?

In the Transferred column everything is cached.

**Comment by ColmMassey** [comment]
![Untitled](https://user-images.githubusercontent.com/1162642/100147598-7e5c9900-2e93-11eb-9255-0ddda1493377.png)

**Comment by wu-lee** [comment]
Even `map-app.js`?  The tiles are cached, but that's actually a good thing.

**Comment by ColmMassey** [comment]
So we identified that there was some very strange behaviour in my version of firefox. Ctrl F5 ensured all the javascript got updated, but it shouldn't have needed to do that. We can close this issue, but will leave a screen shot of the firefox issue here for reference.

**Comment by ColmMassey** [comment]
Actually, lost the screen shot. Nevermind. Essentially firefox didn't seem to be getting the current time and date to check against the last updated time and date for app.js. Nick's FIrefox of Linux worked as expected.
