### ISSUE TITLE
Advanced search options

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#7]
Evaluate options for more advanced searching of ICA members data.

**Comment by ColmMassey** [comment]
Enquiry from ICA "How much would it cost to add a search tool so that we can search by the different map fields, not just country and organisation name but also:
        Super region
        Region
        Typology
        Structure
        Economic activity

To resemble something like https://www.ica.coop/en/our-members/search-our-members

**Comment by ColmMassey** [comment]
I think it breaks down to the following 3 elements.

 - Create vocabularies for ICA's regional clustering. 
 - Support switching between directory filtering categories. https://github.com/SolidarityEconomyAssociation/sea-map/issues/52
 - Extend search panel to also narrow down searches with and operations on the 6 requested categories.

**Comment by ColmMassey** [comment]
2 & 3 may require some exception handling for filtering over Structure, as we have modeled structure as a combination of Organisational Structure and Qualifier.

We also may be required to restrict the options to the subset actuallu used in the data rather than all the options defined in the schema.

**Comment by ColmMassey** [comment]
Can @wu-lee and @dtmakm27 comment on this one? How should we approach interface design for this?

**Comment by dtmakm27** [comment]
in terms of applying filters to grab data, we already have that functionality implemented (when I was reworking the searching and filtering + removing map markers from the map). We're just not using it yet. 

The UI is potentially tricky since it might involve design work and iterating over it. Overall a simple clickable design will take about 1 day to create.

> exception handling for filtering over Structure, as we have modeled structure as a combination of Organisational Structure and Qualifier.
I can't say if this will be a big issue or not until we start implementation so i'd say unknown.



I'd say it will take about 2-4 work days to replicate something like this https://www.ica.coop/en/our-members/search-our-members 
Definitely not a hard task I think

**Comment by ColmMassey** [comment]
I think we should keep it as close as possible to the current design, so I wouldn't bother with multipage listing component
 
![Untitled](https://user-images.githubusercontent.com/1162642/100745064-a3429600-33d6-11eb-9cd2-3880a06416ef.png)

**Comment by ColmMassey** [comment]
We need to support the ability to filter on:

Country - Self evident

Super region - Africa - Americas - Asia+Pacific - Europe - International -

Region - East Africa - North Africa - Southern Africa - West Africa - Caribbean countries - Central America - North America - South America - Central Asia - East Asia - Middle East Europe (Eastern) - South Asia - South East Asia - International - Europe (Western) - Oceania - 

Typology - same as [Base Membership Type VES](https://vocabs.solidarityeconomy.coop/essglobal/V2a/html-content/essglobal.html#H6.2) - Use the Definition 

Structure - Subset of [Organisational Structure VES](https://vocabs.solidarityeconomy.coop/essglobal/V2a/html-content/essglobal.html#H6.1) - Use the Definition of OS115 and then all from OS170 onwards

Economic activity - All of [Economic Activities/Sectors (ICA - L2) VES](https://vocabs.solidarityeconomy.coop/essglobal/V2a/html-content/essglobal.html#H5.2)

**Comment by ColmMassey** [comment]
Can you see this comment @MelissaMc20 ?

**Comment by MelissaMc20** [comment]
> Can you see this comment @MelissaMc20 ?

I can yes - received an email with the comment, no location and no notif on github, so went searching and finally found it here

**Comment by ColmMassey** [comment]
> I can yes - received an email with the comment, no location and no notif on github, so went searching and finally found it here

So there was no url to the Issue in the email notification?

**Comment by MelissaMc20** [comment]
> > I can yes - received an email with the comment, no location and no notif on github, so went searching and finally found it here
> 
> So there was no url to the Issue in the email notification?

I did this time

**Comment by ColmMassey** [comment]
Designs are here

https://xd.adobe.com/view/6461afa1-69f1-496f-8085-475b24888a5c-3132/?fullscreen&hints=off
https://xd.adobe.com/view/5a87561c-9ba7-42c1-ba4c-11fbb1bd1a26-0fd4/?fullscreen&hints=off

https://github.com/SolidarityEconomyAssociation/ica-project/files/5731808/Web.1280.1.pdf

ICA will chose prefered layout in new year and then we can initiate implementation.
