### ISSUE TITLE
Support Internationalisation of sea-map for ICA

### ISSUE THREAD

**Issue by ColmMassey** [SolidarityEconomyAssociation/ica-project#9]
Create a config setting and URL argument which supports the specification of one of 3 supported language, English, French and Spanish for in the app, other than the text in the base map tiles.

There are 2 distinct types of text that could be internationalised:

1 Functionality text in the sea-map 
  - Button names, Panel titles, Panel text, Dialog section headings

2 Data categories & options
  - Structure Type, Typology, Economic Activity…
  - National sectoral federation or union, Consumer/User coops…

Type 1 can be completely implemented in sea-app
Type 2 is best implemented using proper linked data support for internationalisation, so would need the ESSGlobal refactor tob completed and require changes in the front and back ends.

**Comment by ColmMassey** [comment]
The ICA hav provided the following translation of terms for text in the app and the vocab they reference here.

https://nextcloud.solidarityeconomy.coop/index.php/s/i8dNYqbmj7MXrax

Only French translations have been provided so far.

**Comment by ColmMassey** [comment]
Spanish translations are now in :-)

**Comment by King-Mob** [comment]
Today I've added the translations for the labels and titles on sea-map, and added language to the config schema so you can set it in the config, or in the url using e.g. `?language=FR` 

Tomorrow planning to add the translations to the vocabularies and have the dialogue popups for the initiatives be localised as well (they reference the titles of items in the vocabularies, so the vocabularies need to be updated first)

**Comment by King-Mob** [comment]
This is done for sea-map. Still need the alt titles for the "Country" set, as in, the french and spanish words for "Country", then it's all done.

**Comment by ColmMassey** [comment]
Let's go with Pays & País. Is it available to view anywhere yet?

**Comment by King-Mob** [comment]
https://dev.ica.solidarityeconomy.coop/?language=ES

FR for the french version

**Comment by ColmMassey** [comment]
Very cool, but I think someone has gone badly wrong with location data. Nearly everything is now at 0,0!

**Comment by King-Mob** [comment]
Nick is looking into it. The issue is that some of the initiatives have a manual location set, and most of them don't. For some reason the latest data has "no manual location set" as meaning "set the manual location to 0"

Meanwhile, I have pushed a hotfix, so clearing the cache should show you that.

**Comment by ColmMassey** [comment]
@wu-lee dev.ica data is not loading at all at the moment.

Do we need an independent ticket to look at optimising the loading the new vocabs becasue for some reason the most recent functioning dev.ica took an age >12 seconds to load the data?

**Comment by ColmMassey** [comment]
Also we noticed that the entry for All Countries in the directory had need been accomodated. What was missing to support that?

**Comment by King-Mob** [comment]
Need to update the Countries data file so that it has a title in each language. Currently it just has a title in the English vocabulary.

**Comment by wu-lee** [comment]
> @wu-lee dev.ica data is not loading at all at the moment.

dev.ica map seems to work for me?  So does loading data directly via ship-shape.

> Do we need an independent ticket to look at optimising the loading the new vocabs becasue for some reason the most recent functioning dev.ica took an age >12 seconds to load the data?

Seems like we do, if it's taking that long.  (I experience this too.)

**Comment by King-Mob** [comment]
Translations still need:

- Loading
- About page (change how this works, so it comes from the config)
- Map attribution

**Comment by ColmMassey** [comment]
have asked ICA to supply these.

**Comment by ColmMassey** [comment]
![Alliance_trilingual_2021 2](https://user-images.githubusercontent.com/1162642/121521105-93da8000-c9eb-11eb-822f-243a43782460.jpg)

New logo 'without hyphen in co-operative!'

**Comment by King-Mob** [comment]
all done, except waiting for the transparent logo.

I can think that we might want a translation of the word "Map". It appears in the map attribution text and it's the document title as well (title show in tab bar in browser)

**Comment by ColmMassey** [comment]
![Alliance_trilingual_2021](https://user-images.githubusercontent.com/1162642/122957993-5e824a80-d37a-11eb-930b-9ecde397d759.png)

**Comment by King-Mob** [comment]
@ColmMassey live at [https://dev.ica.solidarityeconomy.coop/](https://dev.ica.solidarityeconomy.coop/)

**Comment by ColmMassey** [comment]
Two remaining translation typos

“all countries”

<img width="310" alt="Screen Shot 2021-07-05 at 11 09 32" src="https://user-images.githubusercontent.com/1162642/124772118-a20cb500-df33-11eb-8c3a-bfe361786194.png">
<img width="302" alt="Screen Shot 2021-07-05 at 12 02 55" src="https://user-images.githubusercontent.com/1162642/124772120-a3d67880-df33-11eb-8379-c3994ee31113.png">
Spanish >> Todos los países

French >> Tous les pays

Then add the following values to the config file 

?showDatasetsPanel=False&htmlTitle=ICA&initialBounds=62,-107,-37,174&maxZoomOnOne=10&dialogueSize={"width":"35vw","height":"225px","descriptionRatio":2.5} 


And then can we mirror to the production site. :-)

**Comment by King-Mob** [comment]
I've made a fix for the translation, added those config values and deployed to dev. Requested Nick to deploy to production.

**Comment by ColmMassey** [comment]
@King-Mob I note you made those All Country entries into generic ones rather than refering to countries. Should be fine.
